[uwsgi]
master = true
processes = 5
chdir = /app/iSpaceDoc
wsgi-file = /app/iSpaceDoc/backend/core/wsgi.py
http-socket = 0.0.0.0:8000
logto = /app/iSpaceDoc/log/uwsgi.log
log-maxsize = 3000000
chmod-socket = 664
vacuum = true
enable-threads = true
max-requests = 1000
reload-on-as = 2048
reload-on-rss = 2048
evil-reload-on-as = 2048
evil-reload-on-rss = 2048
buffer-size = 65536
http-timeout = 300
socket-timeout = 300
reload-mercy = 1
worker-reload-mercy = 1
die-on-term = true