# Generated by Django 4.2.30 on 2026-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_registercode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='editor_mode',
            field=models.IntegerField(default=2, verbose_name='编辑器选项'),
        ),
    ]
