# Generated by Django 4.2.30 on 2026-05-19 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_admin', '0011_alter_useroptions_editor_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='配置键')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('delete', '删除'), ('restore', '恢复'), ('grant', '授权'), ('revoke', '撤销权限'), ('login', '登录'), ('role_change', '角色变更')], max_length=20, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, default='', max_length=50, verbose_name='操作对象类型')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='操作对象 ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_admin_a_user_id_d844b5_idx'), models.Index(fields=['action', '-created_at'], name='app_admin_a_action_a4db4f_idx'), models.Index(fields=['target_type', 'target_id'], name='app_admin_a_target__b2ae81_idx')],
            },
        ),
    ]
