# Generated by Django 4.2.30 on 2026-05-19 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_admin', '0012_v1_0_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='登录用户名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='用户代理')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=100, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_admin_l_user_id_33838a_idx'), models.Index(fields=['username', '-created_at'], name='app_admin_l_usernam_4d311b_idx'), models.Index(fields=['ip_address'], name='app_admin_l_ip_addr_b49b3d_idx')],
            },
        ),
    ]
