# Generated by Django 4.2.30 on 2026-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0013_login_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='editor_mode',
            field=models.IntegerField(default=0, verbose_name='编辑器选项'),
        ),
    ]
