# Generated by Django 4.2.30 on 2026-05-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0041_alter_attachment_id_alter_doc_id_alter_dochistory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycollect',
            options={'verbose_name': '我的收藏'},
        ),
        migrations.CreateModel(
            name='DocComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doc.doc', verbose_name='文档')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_doc.doccomment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '文档评论',
                'verbose_name_plural': '文档评论',
                'ordering': ['create_time'],
            },
        ),
    ]
