# Generated by Django 4.2.30 on 2026-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0043_add_doc_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='editor_mode',
            field=models.IntegerField(default=2, verbose_name='编辑器模式'),
        ),
    ]
