# Generated by Django 4.2.30 on 2026-05-19 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0044_alter_doc_editor_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', '用户'), ('group', '分组'), ('org', '组织节点')], max_length=10, verbose_name='授权对象类型')),
                ('target_id', models.PositiveIntegerField(verbose_name='授权对象 ID')),
                ('permission', models.CharField(choices=[('view', '可见'), ('edit', '可编辑'), ('admin', '管理员')], max_length=10, verbose_name='权限级别')),
                ('apply_to_children', models.BooleanField(default=False, verbose_name='同步所有子节点')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
            ],
            options={
                'verbose_name': '文档权限',
                'verbose_name_plural': '文档权限',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='成员数量')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '分组成员',
                'verbose_name_plural': '分组成员',
            },
        ),
        migrations.CreateModel(
            name='InlineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_start', models.PositiveIntegerField(verbose_name='起始字符偏移')),
                ('anchor_end', models.PositiveIntegerField(verbose_name='结束字符偏移')),
                ('anchor_hash', models.CharField(max_length=32, verbose_name='选中文本 MD5')),
                ('selected_text', models.CharField(max_length=500, verbose_name='选中文本原文')),
            ],
            options={
                'verbose_name': '划词评论',
                'verbose_name_plural': '划词评论',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('comment', '文档评论'), ('reply', '评论回复'), ('mention', '@提及'), ('doc_change', '文档变更'), ('doc_like', '文档点赞'), ('perm_apply', '权限申请')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=128, verbose_name='通知标题')),
                ('body', models.TextField(blank=True, default='', verbose_name='通知内容')),
                ('link', models.URLField(blank=True, default='', max_length=500, verbose_name='关联链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='节点名称')),
                ('path', models.CharField(blank=True, default='', max_length=256, verbose_name='物化路径')),
                ('depth', models.PositiveSmallIntegerField(default=0, verbose_name='深度')),
                ('sort_order', models.IntegerField(default=0, verbose_name='同级排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '组织节点',
                'verbose_name_plural': '组织节点',
            },
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主属部门')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '组织成员',
                'verbose_name_plural': '组织成员',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('bio', models.TextField(blank=True, default='', max_length=512, verbose_name='个性说明')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.AddField(
            model_name='doc',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='doc',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_docs', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='doccomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL, verbose_name='@提及的用户'),
        ),
        migrations.AddField(
            model_name='doccomment',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='doccomment',
            name='reply_count',
            field=models.PositiveIntegerField(default=0, verbose_name='回复数'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1, verbose_name='文档状态'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='app_doc_doc_is_dele_4f5d6c_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orguser',
            name='org_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to='app_doc.orgnode'),
        ),
        migrations.AddField(
            model_name='orguser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgnode',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_org_nodes', to=settings.AUTH_USER_MODEL, verbose_name='部门管理员'),
        ),
        migrations.AddField(
            model_name='orgnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_doc.orgnode', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.AddField(
            model_name='inlinecomment',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_comments', to='app_doc.doc', verbose_name='所属文档'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app_doc.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者/管理员'),
        ),
        migrations.AddField(
            model_name='docpermission',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='app_doc.doc', verbose_name='文档'),
        ),
        migrations.AddField(
            model_name='docpermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权人'),
        ),
        migrations.AlterUniqueTogether(
            name='orguser',
            unique_together={('org_node', 'user')},
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_sibling_name'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='app_doc_not_recipie_fa6cf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='docpermission',
            index=models.Index(fields=['doc', 'target_type', 'target_id'], name='app_doc_doc_doc_id_518c59_idx'),
        ),
        migrations.AddIndex(
            model_name='docpermission',
            index=models.Index(fields=['target_type', 'target_id'], name='app_doc_doc_target__19b795_idx'),
        ),
    ]
