# Generated by Django 4.2.30 on 2026-05-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0045_v1_0_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_settings',
            field=models.TextField(blank=True, default='{}', verbose_name='通知设置JSON'),
        ),
    ]
