# Generated by Django 4.2.30 on 2026-05-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0048_v1_0_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_doc.inlinecomment', verbose_name='父评论'),
        ),
    ]
