# Generated by Django 4.2.30 on 2026-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0049_inlinecomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='outline',
            field=models.TextField(blank=True, null=True, verbose_name='文档大纲目录JSON'),
        ),
    ]
