# Generated by Django 4.2.30 on 2026-05-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0050_doc_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', '系统通知'), ('comment', '文档评论'), ('reply', '评论回复'), ('mention', '@提及'), ('doc_change', '文档变更'), ('doc_like', '文档点赞'), ('perm_apply', '权限申请'), ('perm_change', '权限变更')], max_length=20, verbose_name='通知类型'),
        ),
    ]
