# Generated by Django 4.2.30 on 2026-05-25 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0051_groupmember_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('doc', '文档'), ('pro', '文集')], max_length=10, verbose_name='内容类型')),
                ('content_id', models.IntegerField(verbose_name='内容ID')),
                ('extra_id', models.IntegerField(blank=True, null=True, verbose_name='额外ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='浏览时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='app_doc_bro_user_id_b8d464_idx')],
            },
        ),
    ]
