# Generated by Django 4.2.30 on 2026-05-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0053_data_migrate_project_to_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='projectcollaborator',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcollaborator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectreport',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectreportfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttoc',
            name='project',
        ),
        migrations.RemoveIndex(
            model_name='doc',
            name='app_doc_doc_top_doc_09d61d_idx',
        ),
        migrations.AddField(
            model_name='doc',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公开可见'),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_watermark',
            field=models.BooleanField(default=False, verbose_name='水印状态'),
        ),
        migrations.AddField(
            model_name='doc',
            name='watermark_type',
            field=models.IntegerField(default=1, verbose_name='水印类型'),
        ),
        migrations.AddField(
            model_name='doc',
            name='watermark_value',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='水印内容'),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='content_type',
            field=models.CharField(choices=[('doc', '文档')], max_length=10, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='文档状态'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['parent_doc', 'status'], name='app_doc_doc_parent__e2cf57_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['is_public'], name='app_doc_doc_is_publ_483054_idx'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectCollaborator',
        ),
        migrations.DeleteModel(
            name='ProjectReport',
        ),
        migrations.DeleteModel(
            name='ProjectReportFile',
        ),
        migrations.DeleteModel(
            name='ProjectToc',
        ),
    ]
