# Generated by Django 4.2.30 on 2026-05-27 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0054_remove_project_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('url', models.URLField(max_length=500, verbose_name='目标 URL')),
                ('events', models.JSONField(default=list, verbose_name='订阅事件列表')),
                ('secret', models.CharField(blank=True, default='', max_length=128, verbose_name='签名密钥')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'WebHook 配置',
                'verbose_name_plural': 'WebHook 配置',
                'db_table': 'isp_webhook_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebHookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50, verbose_name='事件类型')),
                ('target_url', models.URLField(max_length=500, verbose_name='目标 URL')),
                ('request_body', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('response_status', models.IntegerField(default=0, verbose_name='响应状态码')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='响应体')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('attempt', models.IntegerField(default=1, verbose_name='重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='app_doc.webhookconfig', verbose_name='配置')),
            ],
            options={
                'verbose_name': 'WebHook 投递日志',
                'verbose_name_plural': 'WebHook 投递日志',
                'db_table': 'isp_webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
