# Generated by Django 4.2.30 on 2026-05-27 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0055_v2_0_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件总大小')),
                ('chunk_size', models.IntegerField(verbose_name='分片大小')),
                ('total_chunks', models.IntegerField(verbose_name='总分片数')),
                ('uploaded_chunks', models.JSONField(default=list, verbose_name='已上传分片索引')),
                ('content_type', models.CharField(blank=True, default='', max_length=128, verbose_name='MIME 类型')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('expired', '已过期')], default='uploading', max_length=20, verbose_name='状态')),
                ('storage_key', models.CharField(blank=True, default='', max_length=500, verbose_name='最终存储 Key')),
                ('attachment_id', models.IntegerField(blank=True, null=True, verbose_name='附件记录 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分片上传会话',
                'verbose_name_plural': '分片上传会话',
                'db_table': 'isp_chunked_uploads',
            },
        ),
    ]
