# Generated by Django 4.2.30 on 2026-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0056_v2_0_chunked_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='结构化绘图数据'),
        ),
    ]
