# Generated by Django 4.2.30 on 2026-05-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0057_v2_0_doc_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgnode',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='外部 ID'),
        ),
        migrations.AddField(
            model_name='orgnode',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='外部来源'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dingtalk_userid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='钉钉 UserID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wecom_userid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='企业微信 UserID'),
        ),
    ]
