# Generated by Django 4.2.30 on 2026-05-27 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0058_v2_0_sync_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IspGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, default='', max_length=512, verbose_name='描述')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='成员数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_isp_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '用户分组',
                'verbose_name_plural': '用户分组',
                'db_table': 'isp_groups',
            },
        ),
        migrations.CreateModel(
            name='IspOrgNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('path', models.CharField(blank=True, default='', max_length=512, verbose_name='物化路径')),
                ('depth', models.PositiveSmallIntegerField(default=0, verbose_name='深度')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('external_source', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='外部来源')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='外部 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_nodes', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_doc.isporgnode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '组织节点',
                'verbose_name_plural': '组织节点',
                'db_table': 'isp_org_nodes',
            },
        ),
        migrations.CreateModel(
            name='IspUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, default='', max_length=500, verbose_name='头像 URL')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('bio', models.TextField(blank=True, default='', max_length=512, verbose_name='简介')),
                ('notify_settings', models.JSONField(default=dict, verbose_name='通知设置')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isp_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'isp_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='IspOAuthBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32, verbose_name='提供者')),
                ('provider_user_id', models.CharField(max_length=256, verbose_name='第三方用户 ID')),
                ('provider_user_name', models.CharField(blank=True, default='', max_length=256, verbose_name='第三方用户名')),
                ('extra_data', models.JSONField(default=dict, verbose_name='额外数据')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_bindings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'OAuth 绑定',
                'verbose_name_plural': 'OAuth 绑定',
                'db_table': 'isp_oauth_bindings',
            },
        ),
        migrations.CreateModel(
            name='IspNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('doc.created', '文档创建'), ('doc.updated', '文档更新'), ('doc.published', '文档发布'), ('doc.deleted', '文档删除'), ('doc.restored', '文档恢复'), ('comment.created', '评论新增'), ('comment.replied', '评论回复'), ('perm.granted', '权限授予'), ('perm.revoked', '权限撤销'), ('perm.apply', '权限申请'), ('like.added', '点赞'), ('user.mention', '@提及')], max_length=32, verbose_name='事件类型')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', null=True, verbose_name='正文')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='跳转链接')),
                ('context', models.JSONField(blank=True, default=dict, null=True, verbose_name='上下文数据')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isp_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isp_sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'isp_notifications',
            },
        ),
        migrations.CreateModel(
            name='IspImageGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='分组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '图片分组',
                'verbose_name_plural': '图片分组',
                'db_table': 'isp_image_groups',
            },
        ),
        migrations.CreateModel(
            name='IspImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高度')),
                ('storage_key', models.CharField(max_length=500, verbose_name='存储 Key')),
                ('storage_backend', models.CharField(default='local', max_length=32, verbose_name='存储后端')),
                ('url', models.CharField(blank=True, default='', max_length=1000, verbose_name='访问地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='app_doc.ispimagegroup', verbose_name='分组')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'isp_images',
            },
        ),
        migrations.CreateModel(
            name='IspGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app_doc.ispgroup', verbose_name='分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分组成员',
                'verbose_name_plural': '分组成员',
                'db_table': 'isp_group_members',
            },
        ),
        migrations.CreateModel(
            name='IspDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('content_json', models.JSONField(blank=True, default=dict, null=True, verbose_name='结构化数据')),
                ('content_plain', models.TextField(blank=True, null=True, verbose_name='纯文本')),
                ('sort_order', models.IntegerField(default=9999, verbose_name='排序')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '已归档')], default=1, verbose_name='状态')),
                ('editor_mode', models.IntegerField(choices=[(2, 'Vditor'), (3, 'iceEditor'), (4, 'Luckysheet'), (5, '思维导图'), (6, 'Draw.io'), (7, 'Excalidraw')], default=2, verbose_name='编辑器模式')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开可见')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='软删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('is_watermark', models.BooleanField(default=False, verbose_name='水印开关')),
                ('watermark_type', models.IntegerField(default=1, verbose_name='水印类型')),
                ('watermark_value', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='水印内容')),
                ('outline', models.TextField(blank=True, null=True, verbose_name='大纲 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app_doc.ispdocument', verbose_name='父文档')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'isp_documents',
            },
        ),
        migrations.CreateModel(
            name='IspDocPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('user', '用户'), ('group', '分组'), ('org', '组织节点')], max_length=16, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标 ID')),
                ('permission', models.CharField(choices=[('view', '查看'), ('edit', '编辑'), ('admin', '管理')], max_length=16, verbose_name='权限级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='app_doc.ispdocument', verbose_name='文档')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isp_granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
            ],
            options={
                'verbose_name': '文档权限',
                'verbose_name_plural': '文档权限',
                'db_table': 'isp_doc_permissions',
            },
        ),
        migrations.CreateModel(
            name='IspComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('anchor_id', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='锚点 ID（划词评论）')),
                ('anchor_text', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='锚点文本')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_doc.ispdocument', verbose_name='文档')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_doc.ispcomment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'isp_comments',
            },
        ),
        migrations.CreateModel(
            name='IspAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('content_type', models.CharField(blank=True, default='', max_length=128, verbose_name='MIME 类型')),
                ('storage_key', models.CharField(max_length=500, verbose_name='存储 Key')),
                ('storage_backend', models.CharField(default='local', max_length=32, verbose_name='存储后端')),
                ('download_url', models.CharField(blank=True, default='', max_length=1000, verbose_name='下载地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='app_doc.ispdocument', verbose_name='所属文档')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'isp_attachments',
            },
        ),
        migrations.CreateModel(
            name='IspOrgUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, verbose_name='主属部门')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='职位')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('org_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app_doc.isporgnode', verbose_name='组织节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_assignments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '组织成员',
                'verbose_name_plural': '组织成员',
                'db_table': 'isp_org_users',
                'unique_together': {('org_node', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='isporgnode',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='isp_unique_sibling_name'),
        ),
        migrations.AddIndex(
            model_name='ispoauthbinding',
            index=models.Index(fields=['user', 'provider'], name='isp_oauth_b_user_id_67eb69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ispoauthbinding',
            unique_together={('provider', 'provider_user_id')},
        ),
        migrations.AddIndex(
            model_name='ispnotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='isp_notific_recipie_2bb2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='ispnotification',
            index=models.Index(fields=['event_type'], name='isp_notific_event_t_b9bd30_idx'),
        ),
        migrations.AddIndex(
            model_name='ispimage',
            index=models.Index(fields=['group'], name='isp_images_group_i_e40f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='ispimage',
            index=models.Index(fields=['uploaded_by'], name='isp_images_uploade_a3777a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ispgroupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='ispdocument',
            index=models.Index(fields=['parent', 'status'], name='isp_documen_parent__a81842_idx'),
        ),
        migrations.AddIndex(
            model_name='ispdocument',
            index=models.Index(fields=['sort_order'], name='isp_documen_sort_or_d97dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='ispdocument',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='isp_documen_is_dele_ed3ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='ispdocument',
            index=models.Index(fields=['is_public'], name='isp_documen_is_publ_16331f_idx'),
        ),
        migrations.AddIndex(
            model_name='ispdocument',
            index=models.Index(fields=['created_by'], name='isp_documen_created_467b14_idx'),
        ),
        migrations.AddIndex(
            model_name='ispdocpermission',
            index=models.Index(fields=['target_type', 'target_id'], name='isp_doc_per_target__55717a_idx'),
        ),
        migrations.AddIndex(
            model_name='ispdocpermission',
            index=models.Index(fields=['document', 'permission'], name='isp_doc_per_documen_1f6a80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ispdocpermission',
            unique_together={('document', 'target_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='ispcomment',
            index=models.Index(fields=['document', 'created_at'], name='isp_comment_documen_55b76d_idx'),
        ),
        migrations.AddIndex(
            model_name='ispcomment',
            index=models.Index(fields=['parent'], name='isp_comment_parent__913199_idx'),
        ),
        migrations.AddIndex(
            model_name='ispcomment',
            index=models.Index(fields=['anchor_id'], name='isp_comment_anchor__debe6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ispattachment',
            index=models.Index(fields=['document'], name='isp_attachm_documen_f0da79_idx'),
        ),
        migrations.AddIndex(
            model_name='ispattachment',
            index=models.Index(fields=['storage_key'], name='isp_attachm_storage_c7a0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ispattachment',
            index=models.Index(fields=['uploaded_by'], name='isp_attachm_uploade_389428_idx'),
        ),
    ]
