# Generated by Django 4.2.30 on 2026-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0059_v2_0_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='access_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='访问密码'),
        ),
    ]
