# Generated by Django 4.2.30 on 2026-06-01 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0060_add_doc_access_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='IspContentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='标签颜色')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='引用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_tags', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '内容标签',
                'verbose_name_plural': '内容标签',
                'db_table': 'isp_content_tags',
            },
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '文件附件', 'verbose_name_plural': '文件附件'},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': '文档条目', 'verbose_name_plural': '文档条目'},
        ),
        migrations.AlterModelOptions(
            name='doccomment',
            options={'ordering': ['create_time'], 'verbose_name': '文档讨论', 'verbose_name_plural': '文档讨论'},
        ),
        migrations.AlterModelOptions(
            name='dochistory',
            options={'verbose_name': '文档版本历史', 'verbose_name_plural': '文档版本历史'},
        ),
        migrations.AlterModelOptions(
            name='docshare',
            options={'verbose_name': '分享链接', 'verbose_name_plural': '分享链接'},
        ),
        migrations.AlterModelOptions(
            name='doctag',
            options={'verbose_name': '文档-标签关联', 'verbose_name_plural': '文档-标签关联'},
        ),
        migrations.AlterModelOptions(
            name='doctemp',
            options={'verbose_name': '内容模板', 'verbose_name_plural': '内容模板'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '图片素材', 'verbose_name_plural': '图片素材'},
        ),
        migrations.AlterModelOptions(
            name='imagegroup',
            options={'verbose_name': '图片分组目录', 'verbose_name_plural': '图片分组目录'},
        ),
        migrations.AlterModelOptions(
            name='mycollect',
            options={'verbose_name': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '内容标签', 'verbose_name_plural': '内容标签'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(default='untitled_attachment.zip', max_length=200, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=models.FileField(upload_to='attachment/%Y/%m/', verbose_name='存储路径'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件体积'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='access_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='公开访问密码'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='HTML 渲染内容'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='editor_mode',
            field=models.IntegerField(default=0, verbose_name='编辑器类型'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='允许公开访问'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_watermark',
            field=models.BooleanField(default=False, verbose_name='启用水印'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='open_children',
            field=models.BooleanField(default=False, verbose_name='侧栏默认展开'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='outline',
            field=models.TextField(blank=True, null=True, verbose_name='大纲 JSON'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='parent_doc',
            field=models.IntegerField(default=0, verbose_name='父文档 ID'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='pre_content',
            field=models.TextField(blank=True, null=True, verbose_name='Markdown 源码'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='show_children',
            field=models.BooleanField(default=False, verbose_name='显示所有后代'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='sort',
            field=models.IntegerField(default=9999, verbose_name='同级排序权重'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='top_doc',
            field=models.IntegerField(default=0, verbose_name='根文档 ID'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='watermark_type',
            field=models.IntegerField(default=1, verbose_name='水印样式'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='watermark_value',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='水印文字'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='content',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doc.doc', verbose_name='所属文档'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='显示状态'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL, verbose_name='提及的用户列表'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_doc.doccomment', verbose_name='上级评论'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='reply_count',
            field=models.PositiveIntegerField(default=0, verbose_name='回复计数'),
        ),
        migrations.AlterField(
            model_name='doccomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='dochistory',
            name='pre_content',
            field=models.TextField(blank=True, null=True, verbose_name='历史版本 Markdown 源码'),
        ),
        migrations.AlterField(
            model_name='docshare',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='docshare',
            name='share_value',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='访问口令'),
        ),
        migrations.AlterField(
            model_name='docshare',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分享令牌'),
        ),
        migrations.AlterField(
            model_name='doctemp',
            name='content',
            field=models.TextField(verbose_name='模板正文'),
        ),
        migrations.AlterField(
            model_name='doctemp',
            name='name',
            field=models.CharField(max_length=50, verbose_name='模板标题'),
        ),
        migrations.AlterField(
            model_name='image',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_path',
            field=models.CharField(max_length=250, verbose_name='存储路径'),
        ),
        migrations.AlterField(
            model_name='image',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_doc.imagegroup', verbose_name='所属分组'),
        ),
        migrations.AlterField(
            model_name='image',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
        migrations.AlterField(
            model_name='image',
            name='remark',
            field=models.CharField(blank=True, default='图片描述', max_length=250, null=True, verbose_name='备注描述'),
        ),
        migrations.AlterField(
            model_name='imagegroup',
            name='group_name',
            field=models.CharField(default='默认分组', max_length=50, verbose_name='分组名'),
        ),
        migrations.AlterField(
            model_name='ispdocument',
            name='editor_mode',
            field=models.IntegerField(choices=[(0, 'Markdown'), (1, '电子表格')], default=0, verbose_name='编辑器模式'),
        ),
        migrations.AlterField(
            model_name='mycollect',
            name='collect_id',
            field=models.IntegerField(verbose_name='收藏目标 ID'),
        ),
        migrations.AlterField(
            model_name='mycollect',
            name='collect_type',
            field=models.IntegerField(verbose_name='收藏对象类别'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10, verbose_name='标签名称'),
        ),
        migrations.CreateModel(
            name='IspUserBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookmark_type', models.CharField(choices=[('doc', '文档')], max_length=16, verbose_name='收藏类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='收藏目标 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'isp_user_bookmarks',
                'indexes': [models.Index(fields=['user', 'bookmark_type'], name='isp_user_bo_user_id_267843_idx'), models.Index(fields=['created_at'], name='isp_user_bo_created_e05d7f_idx')],
                'unique_together': {('user', 'bookmark_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='IspShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True, verbose_name='分享令牌')),
                ('access_level', models.CharField(choices=[('public', '公开访问'), ('code', '口令访问')], default='public', max_length=16, verbose_name='访问模式')),
                ('access_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='访问口令')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('max_views', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大浏览数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_links', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='app_doc.ispdocument', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '分享链接',
                'verbose_name_plural': '分享链接',
                'db_table': 'isp_share_links',
                'indexes': [models.Index(fields=['token'], name='isp_share_l_token_9c4228_idx'), models.Index(fields=['document', 'is_active'], name='isp_share_l_documen_8b83ed_idx'), models.Index(fields=['expires_at'], name='isp_share_l_expires_043499_idx')],
            },
        ),
        migrations.CreateModel(
            name='IspDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('markdown_content', models.TextField(blank=True, null=True, verbose_name='Markdown 内容快照')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='HTML 内容快照')),
                ('change_summary', models.CharField(blank=True, default='', max_length=256, verbose_name='变更摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app_doc.ispdocument', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '文档版本历史',
                'verbose_name_plural': '文档版本历史',
                'db_table': 'isp_document_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['document', '-version_number'], name='isp_documen_documen_641b86_idx'), models.Index(fields=['created_at'], name='isp_documen_created_27c5cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='IspDocumentTagRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tagged_at', models.DateTimeField(auto_now_add=True, verbose_name='标记时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_refs', to='app_doc.ispdocument', verbose_name='文档')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_refs', to='app_doc.ispcontenttag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文档-标签关联',
                'verbose_name_plural': '文档-标签关联',
                'db_table': 'isp_document_tags',
                'indexes': [models.Index(fields=['tag'], name='isp_documen_tag_id_8535b0_idx'), models.Index(fields=['document'], name='isp_documen_documen_ec78a4_idx')],
                'unique_together': {('document', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='IspDocumentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app_doc.ispdocument', verbose_name='文档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文档点赞',
                'verbose_name_plural': '文档点赞',
                'db_table': 'isp_document_likes',
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='IspContentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='模板标题')),
                ('body', models.TextField(verbose_name='模板正文')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='分类')),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('shared', '团队共享')], default='private', max_length=16, verbose_name='可见范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '内容模板',
                'verbose_name_plural': '内容模板',
                'db_table': 'isp_content_templates',
                'indexes': [models.Index(fields=['created_by', 'category'], name='isp_content_created_1eada7_idx'), models.Index(fields=['visibility'], name='isp_content_visibil_e6be33_idx')],
            },
        ),
        migrations.CreateModel(
            name='IspBrowseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('doc', '文档')], max_length=16, verbose_name='内容类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='内容 ID')),
                ('context_id', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='上下文 ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='浏览时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browse_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'db_table': 'isp_browse_records',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='isp_browse__user_id_df2b44_idx'), models.Index(fields=['target_type', 'target_id'], name='isp_browse__target__fd20f2_idx')],
            },
        ),
    ]
